In [244]:
import pandas as pd
import numpy as np

In [245]:
"""

Part - 1 (Credit Transaction data)

"""

'\n\nPart - 1 (Credit Transaction data)\n\n'

In [246]:
data = pd.read_csv("~/Desktop/files/Homework4_Dataset/res_purchase_2014.csv", sep= ",")

In [247]:
data.head()

,Year-Month,Agency Number,Agency Name,Cardholder Last Name,Cardholder First Initial,Description,Amount,Vendor,Transaction Date,Posted Date,Merchant Category Code (MCC)
0,201307,1000,OKLAHOMA STATE UNIVERSITY,Mason,C,GENERAL PURCHASE,890,NACAS,7/30/2013 0:00,7/31/2013 0:00,CHARITABLE AND SOCIAL SERVICE ORGANIZATIONS
1,201307,1000,OKLAHOMA STATE UNIVERSITY,Mason,C,ROOM CHARGES,368.96,SHERATON HOTEL,7/30/2013 0:00,7/31/2013 0:00,SHERATON
2,201307,1000,OKLAHOMA STATE UNIVERSITY,Massey,J,GENERAL PURCHASE,165.82,SEARS.COM 9300,7/29/2013 0:00,7/31/2013 0:00,DIRCT MARKETING/DIRCT MARKETERS--NOT ELSEWHERE...
3,201307,1000,OKLAHOMA STATE UNIVERSITY,Massey,T,GENERAL PURCHASE,96.39,WAL-MART #0137,7/30/2013 0:00,7/31/2013 0:00,"GROCERY STORES,AND SUPERMARKETS"
4,201307,1000,OKLAHOMA STATE UNIVERSITY,Mauro-Herrera,M,HAMMERMILL COPY PLUS COPY EA,125.96,STAPLES DIRECT,7/30/2013 0:00,7/31/2013 0:00,"STATIONERY, OFFICE SUPPLIES, PRINTING AND WRIT..."

In [248]:
df_purchase = pd.DataFrame(data=data)

In [249]:
def missing_values(x):
    return sum(x.isnull())
df.apply(missing_values, axis=0)

Year-Month                      0
Agency Number                   0
Agency Name                     0
Cardholder Last Name            0
Cardholder First Initial        0
Description                     0
Amount                          0
Vendor                          0
Transaction Date                0
Posted Date                     0
Merchant Category Code (MCC)    0
dtype: int64

In [250]:
df_purchase['Amount'] = (df_purchase['Amount'].replace( '[\$,)]','', regex=True ).replace( '[(]','-',   regex=True ).replace(r'[^\d.]+', '',   regex=True ).astype(float))
df_purchase.head()

,Year-Month,Agency Number,Agency Name,Cardholder Last Name,Cardholder First Initial,Description,Amount,Vendor,Transaction Date,Posted Date,Merchant Category Code (MCC)
0,201307,1000,OKLAHOMA STATE UNIVERSITY,Mason,C,GENERAL PURCHASE,890.00,NACAS,7/30/2013 0:00,7/31/2013 0:00,CHARITABLE AND SOCIAL SERVICE ORGANIZATIONS
1,201307,1000,OKLAHOMA STATE UNIVERSITY,Mason,C,ROOM CHARGES,368.96,SHERATON HOTEL,7/30/2013 0:00,7/31/2013 0:00,SHERATON
2,201307,1000,OKLAHOMA STATE UNIVERSITY,Massey,J,GENERAL PURCHASE,165.82,SEARS.COM 9300,7/29/2013 0:00,7/31/2013 0:00,DIRCT MARKETING/DIRCT MARKETERS--NOT ELSEWHERE...
3,201307,1000,OKLAHOMA STATE UNIVERSITY,Massey,T,GENERAL PURCHASE,96.39,WAL-MART #0137,7/30/2013 0:00,7/31/2013 0:00,"GROCERY STORES,AND SUPERMARKETS"
4,201307,1000,OKLAHOMA STATE UNIVERSITY,Mauro-Herrera,M,HAMMERMILL COPY PLUS COPY EA,125.96,STAPLES DIRECT,7/30/2013 0:00,7/31/2013 0:00,"STATIONERY, OFFICE SUPPLIES, PRINTING AND WRIT..."

In [251]:
# What is total amount spending captured in this dataset?
df_purchase['Amount'].sum()

188780963.7699999

In [252]:
def sum_of(name):
    return df_purchase['Amount'][df_purchase['Vendor'] == name].sum()

In [253]:
# How much was spend at WW GRAINGER?
n1 = "WW GRAINGER"
sum_of(n1)

5103078.5200000005

In [254]:
#How much was spend at WM SUPERCENTER?
n2 = "WM SUPERCENTER"
sum_of(n2)

31777.83

In [255]:
#How much was spend at GROCERY STORES?
n3 = "GROCERY STORES"
sum_of(n3)

0.0

In [256]:
"""

Part - 2 (Data Processing with Pandas)

"""

'\n\nPart - 2 (Data Processing with Pandas)\n\n'

In [257]:
"""
1. Read’Energy.xlsx’and’EnergyRating.xlsx’asBalanceSheetandRatings(dataframe).
"""
BalanceSheet = pd.read_excel("~/Desktop/files/Homework4_Dataset/Energy.xlsx")
Ratings = pd.read_excel("~/Desktop/files/Homework4_Dataset/EnergyRating.xlsx")
BalanceSheet.head()

,Global Company Key,Data Date,Fiscal Year,Fiscal Quarter,Fiscal Year-end Month,Industry Format,Level of Consolidation - Company Interim Descriptor,Population Source,Data Format,Ticker Symbol,...,Implied Option EPS Basic,Implied Option EPS Basic Preliminary,Implied Option Expense,Implied Option Expense Preliminary,Research and Development Expense,"Selling, General and Administrative Expenses",Stock Exchange Code,CIK Number,Active/Inactive Status Marker,Current ISO Country Code - Incorporation
0,1380,20100331,2010,1,12,INDL,C,D,STD,HES,...,0.0,0.0,0.0,0.0,NaN,559.0,11,4447,A,USA
1,1380,20100630,2010,2,12,INDL,C,D,STD,HES,...,0.0,0.0,0.0,0.0,NaN,576.0,11,4447,A,USA
2,1380,20100930,2010,3,12,INDL,C,D,STD,HES,...,0.0,0.0,0.0,0.0,NaN,608.0,11,4447,A,USA
3,1380,20101231,2010,4,12,INDL,C,D,STD,HES,...,0.0,0.0,0.0,0.0,NaN,805.0,11,4447,A,USA
4,1380,20110331,2011,1,12,INDL,C,D,STD,HES,...,0.0,0.0,0.0,0.0,NaN,760.0,11,4447,A,USA

In [258]:
Ratings.head()

,Global Company Key,S&P Domestic Long Term Issuer Credit Rating,S&P Subordinated Debt Rating,S&P Domestic Short Term Issuer Credit Rating,Data Date,Address Line 1,Ticker Symbol
0,1380,BBB-,NaN,NaN,20100131,"1185 Avenue of the Americas, 40th Floor",HES
1,1380,BBB-,NaN,NaN,20100228,"1185 Avenue of the Americas, 40th Floor",HES
2,1380,BBB-,NaN,NaN,20100331,"1185 Avenue of the Americas, 40th Floor",HES
3,1380,BBB-,NaN,NaN,20100430,"1185 Avenue of the Americas, 40th Floor",HES
4,1380,BBB-,NaN,NaN,20100531,"1185 Avenue of the Americas, 40th Floor",HES

In [259]:
BalanceSheet.columns

Index(['Global Company Key', 'Data Date', 'Fiscal Year', 'Fiscal Quarter',
       'Fiscal Year-end Month', 'Industry Format',
       'Level of Consolidation - Company Interim Descriptor',
       'Population Source', 'Data Format', 'Ticker Symbol',
       ...
       'Implied Option EPS Basic', 'Implied Option EPS Basic Preliminary',
       'Implied Option Expense', 'Implied Option Expense Preliminary',
       'Research and Development Expense',
       'Selling, General and Administrative Expenses', 'Stock Exchange Code',
       'CIK Number', 'Active/Inactive Status Marker',
       'Current ISO Country Code - Incorporation'],
      dtype='object', length=380)

In [260]:
BalanceSheet

,Global Company Key,Data Date,Fiscal Year,Fiscal Quarter,Fiscal Year-end Month,Industry Format,Level of Consolidation - Company Interim Descriptor,Population Source,Data Format,Ticker Symbol,...,Implied Option EPS Basic,Implied Option EPS Basic Preliminary,Implied Option Expense,Implied Option Expense Preliminary,Research and Development Expense,"Selling, General and Administrative Expenses",Stock Exchange Code,CIK Number,Active/Inactive Status Marker,Current ISO Country Code - Incorporation
0,1380,20100331,2010,1,12,INDL,C,D,STD,HES,...,0.0,0.0,0.0,0.0,NaN,559.0,11,4447,A,USA
1,1380,20100630,2010,2,12,INDL,C,D,STD,HES,...,0.0,0.0,0.0,0.0,NaN,576.0,11,4447,A,USA
2,1380,20100930,2010,3,12,INDL,C,D,STD,HES,...,0.0,0.0,0.0,0.0,NaN,608.0,11,4447,A,USA
3,1380,20101231,2010,4,12,INDL,C,D,STD,HES,...,0.0,0.0,0.0,0.0,NaN,805.0,11,4447,A,USA
4,1380,20110331,2011,1,12,INDL,C,D,STD,HES,...,0.0,0.0,0.0,0.0,NaN,760.0,11,4447,A,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
839,186989,20151231,2015,4,12,INDL,C,D,STD,MPC,...,NaN,NaN,NaN,NaN,NaN,403.0,11,1510295,A,USA
840,186989,20160331,2016,1,12,INDL,C,D,STD,MPC,...,NaN,NaN,NaN,NaN,NaN,378.0,11,1510295,A,USA
841,186989,20160630,2016,2,12,INDL,C,D,STD,MPC,...,NaN,NaN,NaN,NaN,NaN,401.0,11,1510295,A,USA
842,186989,20160930,2016,3,12,INDL,C,D,STD,MPC,...,NaN,NaN,NaN,NaN,NaN,420.0,11,1510295,A,USA
843,186989,20161231,2016,4,12,INDL,C,D,STD,MPC,...,NaN,NaN,NaN,NaN,NaN,406.0,11,1510295,A,USA

In [261]:
Ratings.columns

Index(['Global Company Key', 'S&P Domestic Long Term Issuer Credit Rating',
       'S&P Subordinated Debt Rating',
       'S&P Domestic Short Term Issuer Credit Rating', 'Data Date',
       'Address Line 1', 'Ticker Symbol'],
      dtype='object')

In [262]:
"""
2. drop the column if more than 90% value in this colnmn is 0. (Hint, using pd.apply() function)
"""
col_bs = list()
for columns in BalanceSheet.columns:
    if (BalanceSheet[columns]==0).mean()>0.9:
        col_bs.append(columns)

In [263]:
col_bs

['Accounting Changes - Cumulative Effect',
 'Accum Other Comp Inc - Unreal G/L Ret Int in Sec Assets',
 'Dividends - Preferred/Preference',
 'Common ESOP Obligation - Total',
 'Preferred ESOP Obligation - Total',
 'Noncontrolling Interest - Redeemable - Balance Sheet',
 'Nonred Pfd Shares Outs (000) - Quarterly',
 'Redeem Pfd Shares Outs (000)',
 'Preferred/Preference Stock - Nonredeemable',
 'Preferred/Preference Stock (Capital) - Total',
 'Preferred/Preference Stock - Redeemable',
 'Extraordinary Items']

In [264]:
balancesheet = BalanceSheet.drop(columns=col_bs,axis = 1)

In [265]:
for columns in balancesheet.columns:
    print(columns)

Global Company Key
Data Date
Fiscal Year
Fiscal Quarter
Fiscal Year-end Month
Industry Format
Level of Consolidation - Company Interim Descriptor
Population Source
Data Format
Ticker Symbol
CUSIP
Company Name
ISO Currency Code
Calendar Data Year and Quarter
Fiscal Data Year and Quarter
Accumulated Other Comprehensive Income (Loss)
Current Assets - Other - Total
Current Assets - Total
Other Long-term Assets
Non-Current Assets - Total
Assets Netting & Other Adjustments
Accum Other Comp Inc - Derivatives Unrealized Gain/Loss
Accum Other Comp Inc - Other Adjustments
Accum Other Comp Inc - Min Pension Liab Adj
Assets Level2 (Observable)
Assets - Other - Total
Account Payable/Creditors - Trade
Acquisition/Merger After-Tax
Acquisition/Merger Diluted EPS Effect
Acquisition/Merger Basic EPS Effect
Assets Level1 (Quoted Prices)
Acquisition/Merger Pretax
As Reported Core - Diluted EPS Effect
As Reported Core - Basic EPS Effect
As Reported Core - After-tax
Assets - Total
Assets Level3 (Unobservable)
Billings in Excess of Cost & Earnings
Risk-Adjusted Capital Ratio - Tier 1
Risk-Adjusted Capital Ratio - Tier 2
Risk-Adjusted Capital Ratio - Combined
Capitalized Software
Capital Surplus/Share Premium Reserve
Cost & Earnings in Excess of Billings
Common/Ordinary Equity - Total
Cash and Short-Term Investments
Cash
Comp Inc - Beginning Net Income
Comp Inc - Currency Trans Adj
Comp Inc - Derivative Gains/Losses
Comprehensive Income - Noncontrolling Interest
Comp Inc - Other Adj
Comp Inc - Minimum Pension Adj
Comprehensive Income - Total
Comp Inc - Securities Gains/Losses
Comprehensive Income - Parent
Cost of Goods Sold
Common Shares Used to Calculate Earnings Per Share - 12 Months Moving
Common Shares Used to Calc Earnings Per Share - Fully Diluted - 12 Months Moving
Com Shares for Diluted EPS
Common Shares Issued
Total Shares Repurchased - Quarter
Common Shares Outstanding
Common Shares Used to Calculate Earnings Per Share - Basic
Carrying Value
Common Stock Equivalents - Dollar Savings
Common/Ordinary Stock (Capital)
Deferred Compensation
Long-Term Debt Due in One Year
Derivative Assets - Current
Derivative Assets Long-Term
Gains/Losses on Derivatives and Hedging
Derivative Liabilities- Current
Derivative Liabilities Long-Term
Dilution Adjustment
Dilution Available - Excluding Extraordinary Items
Debt in Current Liabilities
Long-Term Debt - Total
Discontinued Operations
Accumulated Depreciation of RE Property
Depreciation, Depletion and Amortization (Accumulated)
Depreciation and Amortization - Total
Depr/Amort of Property
Deferred Revenue - Current
Deferred Revenue - Long-term
Extinguishment of Debt After-tax
Extinguishment of Debt Diluted EPS Effect
Extinguishment of Debt Basic EPS Effect
Extinguishment of Debt Pretax
Dividends & Interest Receivable (Cash Flow)
Earnings Per Share (Diluted) - Excluding Extraordinary Items - 12 Months Moving
Earnings Per Share (Diluted) - Including Extraordinary Items 12MM
Earnings Per Share (Diluted) - Including Extraordinary Items
Earnings Per Share (Diluted) - Excluding Extraordinary items
Earnings Per Share (Basic) - Including Extraordinary Items - 12 Months Moving
Earnings Per Share (Basic) - Including Extraordinary Items
Earnings Per Share (Basic) - Excluding Extraordinary Items
Earnings Per Share (Basic) - Excluding Extraordinary Items - 12 Months Moving
Preferred ESOP Obligation - Non-Redeemable
Preferred ESOP Obligation - Redeemable
Equity in Earnings (I/S) - Unconsolidated Subsidiaries
Foreign Exchange Income (Loss)
Funds From Operations (REIT)
Finance Division Other Current Assets, Total
Finance Division Other Long-Term Assets, Total
Finance Division - Cash
Finance Division Long-Term Debt  Current
Finance Division Debt  Long-Term
Finance Division  Short-Term Investments
Finance Division Other Current Liabilities, Total
Finance Division Other Long Term Liabilities, Total
Finance Division Notes Payable
Finance Division  Current Receivables
Finance Division  Long-Term Receivables
Finance Division Revenue
Finance Division Interest Expense
Finance Division Operating Expense
Amortization of Goodwill
Impairments of Goodwill AfterTax - 12mm
Impairment of Goodwill After-tax
Impairments Diluted EPS - 12mm
Impairment of Goodwill Diluted EPS Effect
Impairment of Goodwill Basic EPS Effect 12MM
Impairment of Goodwill Basic EPS Effect
Impairment of Goodwill Pretax
Goodwill (net)
Gain/Loss After-Tax
Gain/Loss on Sale (Core Earnings Adjusted) After-tax 12MM
Gain/Loss on Sale (Core Earnings Adjusted) After-tax
Gain/Loss on Sale (Core Earnings Adjusted) Diluted EPS Effect 12MM
Gain/Loss on Sale (Core Earnings Adjusted) Diluted EPS
Gain/Loss on Sale (Core Earnings Adjusted) Basic EPS Effect 12MM
Gain/Loss on Sale (Core Earnings Adjusted) Basic EPS Effect
Gain/Loss on Sale (Core Earnings Adjusted) Pretax
Gain/Loss Diluted EPS Effect
Gain/Loss Basic EPS Effect
Gains/Losses on investments
Gain/Loss Pretax
Gain/Loss on Ineffective Hedges
Income Before Extra Items - Adj for Common Stock Equivalents - 12MM
Income Before Extraordinary Items - Adjusted for Common Stock Equivalents
Income Before Extraordinary Items - Available for Common
Income before Extraordinary Items and Noncontrolling Interests
Income Before Extraordinary Items
Invested Capital - Total - Quarterly
Interest Accrued
Other Intangibles
Intangible Assets - Total
Inventory - Finished Goods
Inventory - Other
Inventory - Raw Materials
Inventories - Total
Inventory - Work in Process
Investment and Advances - Equity
Investment and Advances - Other
Total Long-term Investments
Short-Term Investments- Total
Current Liabilities - Other - Total
Current Liabilities - Total
Long-Term Liabilities (Total)
Liabilities Netting & Other Adjustments
Liabilities Level2 (Observable)
Liabilities - Other
Liabilities - Other - Excluding Deferred Revenue
Liabilities Level1 (Quoted Prices)
Liabilities and Stockholders Equity - Total
Liabilities - Total and Noncontrolling Interest
Liabilities - Total
Liabilities Level3 (Unobservable)
Noncontrolling Interests - Nonredeemable - Balance Sheet
Noncontrolling Interests - Total - Balance Sheet
Noncontrolling Interest - Income Account
Accum Other Comp Inc - Marketable Security Adjustments
Net Charge-Offs
Net Interest Income (Tax Equivalent)
Net Interest Margin
Net Income (Loss)
Non-Operating Income (Expense) - Total
Nonperforming Assets - Total
Notes Payable
Nonrecurring Income Taxes Diluted EPS Effect
Nonrecurring Income Taxes Basic EPS Effect
Nonrecurring Income Taxes - After-tax
Order backlog
Earnings Per Share - Diluted - from Operations - 12MM
Earnings Per Share from Operations - 12 Months Moving
Earnings Per Share - Diluted - from Operations
Operating Income After Depreciation - Quarterly
Operating Income Before Depreciation - Quarterly
Earnings Per Share from Operations
Dividend Rate - Assumption (%)
Options - Fair Value of Options Granted
Life of Options - Assumption (# yrs)
Risk Free Rate - Assumption (%)
Volatility - Assumption (%)
Pretax Income
Provision for Loan/Asset Losses
Pension Core Adjustment - 12mm
Core Pension Adjustment Diluted EPS Effect 12MM
Core Pension Adjustment Diluted EPS Effect
Core Pension Adjustment Basic EPS Effect 12MM
Core Pension Adjustment Basic EPS Effect
Core Pension Interest Adjustment After-tax Preliminary
Core Pension Interest Adjustment After-tax
Core Pension Interest Adjustment Diluted EPS Effect Preliminary
Core Pension Interest Adjustment Diluted EPS Effect
Core Pension Interest Adjustment Basic EPS Effect Preliminary
Core Pension Interest Adjustment Basic EPS Effect
Core Pension Interest Adjustment Pretax Preliminary
Core Pension Interest Adjustment Pretax
Core Pension Adjustment 12MM Diluted EPS Effect Preliminary
Core Pension Adjustment Diluted EPS Effect Preliminary
Core Pension Adjustment 12MM Basic EPS Effect Preliminary
Core Pension Adjustment Basic EPS Effect Preliminary
Core Pension Adjustment Preliminary
Core Pension Adjustment
Core Pension w/o Interest Adjustment After-tax Preliminary
Core Pension w/o Interest Adjustment After-tax
Core Pension w/o Interest Adjustment Diluted EPS Effect Preliminary
Core Pension w/o Interest Adjustment Diluted EPS Effect
Core Pension w/o Interest Adjustment Basic EPS Effect Preliminary
Core Pension w/o Interest Adjustment Basic EPS Effect
Core Pension w/o Interest Adjustment Pretax Preliminary
Core Pension w/o Interest Adjustment Pretax
Property, Plant and Equipment - Total (Gross) - Quarterly
Property Plant and Equipment - Total (Net)
Core Post Retirement Adjustment
Core Post Retirement Adjustment Diluted EPS Effect 12MM
Core Post Retirement Adjustment Diluted EPS Effect
Core Post Retirement Adjustment 12MM
Core Post Retirement Adjustment Basic EPS Effect 12MM
Core Post Retirement Adjustment Basic EPS Effect
Core Post Retirement Adjustment 12MM Diluted EPS Effect Preliminary
Core Post Retirement Adjustment Diluted EPS Effect Preliminary
Core Post Retirement Adjustment 12MM Basic EPS Effect Preliminary
Core Post Retirement Adjustment Basic EPS Effect Preliminary
Core Post Retirement Adjustment Preliminary
Repurchase Price - Average per share Quarter
Restructuring Cost After-tax
Restructuring Cost Diluted EPS Effect
Restructuring Cost Basic EPS Effect
Restructuring Cost Pretax
In Process R&D Expense After-tax
In Process R&D Expense Diluted EPS Effect
In Process R&D Expense Basic EPS Effect
In Process R&D
Receivables - Estimated Doubtful
Accum Other Comp Inc - Cumulative Translation Adjustments
Receivables - Current Other incl Tax Refunds
Receivables - Total
Receivables - Trade
Unbilled Receivables - Quarterly
Retained Earnings
Total RE Property
Unadjusted Retained Earnings
Revenue - Total
Reserve for Loan/Asset Losses
Reversal - Restructruring/Acquisition Aftertax 12MM
Reversal - Restructruring/Acquisition Aftertax
Reversal - Restructuring/Acq Diluted EPS Effect 12MM
Reversal - Restructuring/Acq Diluted EPS Effect
Reversal - Restructuring/Acq Basic EPS Effect 12MM
Reversal - Restructuring/Acq Basic EPS Effect
Reversal - Restructruring/Acquisition Pretax
Long-Term Restricted Cash & Investments
Restricted Cash & Investments - Current
Sales/Turnover (Net)
Other Stockholders- Equity Adjustments
Stockholders Equity > Parent > Index Fundamental > Quarterly
Settlement (Litigation/Insurance) AfterTax - 12mm
Settlement (Litigation/Insurance) After-tax
Settlement (Litigation/Insurance) Diluted EPS Effect 12MM
Settlement (Litigation/Insurance) Diluted EPS Effect
Settlement (Litigation/Insurance) Basic EPS Effect 12MM
Settlement (Litigation/Insurance) Basic EPS Effect
Settlement (Litigation/Insurance) Pretax
S&P Core Earnings 12MM
S&P Core Earnings EPS Diluted 12MM
S&P Core Earnings EPS Diluted - Preliminary
S&P Core Earnings EPS Diluted
S&P Core Earnings EPS Basic 12MM
S&P Core 12MM EPS - Basic - Preliminary
S&P Core Earnings EPS Basic - Preliminary
S&P Core Earnings EPS Basic
S&P Core Earnings 12MM - Preliminary
S&P Core Earnings 12MM EPS Diluted - Preliminary
S&P Core Earnings - Preliminary
S&P Core Earnings
Other Special Items Diluted EPS Effect
Other Special Items Basic EPS Effect
Other Special Items After-tax
Other Special Items Pretax
Special Items
Gain/Loss on Sale of Property
Stock Compensation Expense
After-tax stock compensation
Stockholders Equity - Total
Total Fair Value Assets
Total Fair Value Changes including Earnings
Total Fair Value Liabilities
Interest Expense - Total (Financial Services)
Interest Income - Total (Financial Services)
Treasury Stock - Number of Common Shares
Treasury Stock - Total (All Capital)
Deferred Tax Asset - Long Term
Current Deferred Tax Asset
Current Deferred Tax Liability
Deferred Taxes - Balance Sheet
Income Taxes - Deferred
Deferred Taxes and Investment Tax Credit
Income Taxes Payable
Income Taxes - Total
Excise Taxes
Current Assets - Other - Utility
Other Assets - Utility
Accounts Payable - Utility
Paid In Capital - Other - Utility
Contributions In Aid Of Construction
Common Equity - Total - Utility
Debt (Debentures) - Utility
Debt (Mortgage Bonds)
Debt (Other Long-Term)
Debt (Pollution Control Obligations)
Preferred Dividend Requirements
Gross Income (Income Before Interest Charges)
Inventories
Current Liabilities - Other
Net Income before Extraordinary Items After Noncontrolling Interest
Nonoperating Income (Net) - Other
Operating Income - Total - Utility
Preference Dividend Requirements - Utility
Premium On Common Stock - Utility
Premium On Preferred Stock - Utility
Premium On Preference Stock - Utility
Premium On Subsidiary Preferred Stock - Utility
Preference Stock At Carrying Value - Utility
Preferred Stock At Carrying Value - Utility
Receivables (Net) - Utility
Special Items - Utility
Subsidiary Preferred Dividends - Utility
Subsidiary Preferred Stock At Carrying Value - Utility
Maintenance Expense - Total
Working Capital (Balance Sheet)
Writedowns After-tax
Writedowns Diluted EPS Effect
Writedowns Basic EPS Effect
Writedowns Pretax
Accrued Expenses
Extraordinary Items and Discontinued Operations
Interest and Related Expense- Total
Operating Expense- Total
Implied Option Expense - 12mm
Implied Option EPS Diluted 12MM
Implied Option 12MM EPS Diluted Preliminary
Implied Option EPS Diluted
Implied Option EPS Diluted Preliminary
Implied Option EPS Basic 12MM
Implied Option 12MM EPS Basic Preliminary
Implied Option EPS Basic
Implied Option EPS Basic Preliminary
Implied Option Expense
Implied Option Expense Preliminary
Research and Development Expense
Selling, General and Administrative Expenses
Stock Exchange Code
CIK Number
Active/Inactive Status Marker
Current ISO Country Code - Incorporation

In [266]:
col_ratings = list()
for columns in Ratings.columns:
    if (Ratings[columns]==0).mean()>0.9:
        col_ratings.append(columns)

In [267]:
col_ratings

[]

In [268]:
ratings = Ratings.drop(columns=col_ratings,axis = 1)

In [269]:
# function for printing na values
def number_of_nan(col, df):
    sth = df[col].isnull().sum()
    print(col,"     ",sth)

In [270]:
# na values in balancesheet
for columns in balancesheet.columns:
    number_of_nan(columns, balancesheet)

Global Company Key       0
Data Date       0
Fiscal Year       0
Fiscal Quarter       0
Fiscal Year-end Month       0
Industry Format       0
Level of Consolidation - Company Interim Descriptor       0
Population Source       0
Data Format       0
Ticker Symbol       0
CUSIP       0
Company Name       0
ISO Currency Code       0
Calendar Data Year and Quarter       0
Fiscal Data Year and Quarter       0
Accumulated Other Comprehensive Income (Loss)       29
Current Assets - Other - Total       14
Current Assets - Total       14
Other Long-term Assets       98
Non-Current Assets - Total       98
Assets Netting & Other Adjustments       149
Accum Other Comp Inc - Derivatives Unrealized Gain/Loss       78
Accum Other Comp Inc - Other Adjustments       31
Accum Other Comp Inc - Min Pension Liab Adj       63
Assets Level2 (Observable)       149
Assets - Other - Total       14
Account Payable/Creditors - Trade       14
Acquisition/Merger After-Tax       743
Acquisition/Merger Diluted EPS Effect       743
Acquisition/Merger Basic EPS Effect       743
Assets Level1 (Quoted Prices)       149
Acquisition/Merger Pretax       724
As Reported Core - Diluted EPS Effect       844
As Reported Core - Basic EPS Effect       844
As Reported Core - After-tax       844
Assets - Total       14
Assets Level3 (Unobservable)       149
Billings in Excess of Cost & Earnings       828
Risk-Adjusted Capital Ratio - Tier 1       844
Risk-Adjusted Capital Ratio - Tier 2       844
Risk-Adjusted Capital Ratio - Combined       844
Capitalized Software       828
Capital Surplus/Share Premium Reserve       35
Cost & Earnings in Excess of Billings       828
Common/Ordinary Equity - Total       13
Cash and Short-Term Investments       14
Cash       14
Comp Inc - Beginning Net Income       16
Comp Inc - Currency Trans Adj       55
Comp Inc - Derivative Gains/Losses       44
Comprehensive Income - Noncontrolling Interest       16
Comp Inc - Other Adj       18
Comp Inc - Minimum Pension Adj       43
Comprehensive Income - Total       16
Comp Inc - Securities Gains/Losses       33
Comprehensive Income - Parent       16
Cost of Goods Sold       11
Common Shares Used to Calculate Earnings Per Share - 12 Months Moving       8
Common Shares Used to Calc Earnings Per Share - Fully Diluted - 12 Months Moving       8
Com Shares for Diluted EPS       8
Common Shares Issued       43
Total Shares Repurchased - Quarter       231
Common Shares Outstanding       20
Common Shares Used to Calculate Earnings Per Share - Basic       8
Carrying Value       60
Common Stock Equivalents - Dollar Savings       8
Common/Ordinary Stock (Capital)       35
Deferred Compensation       104
Long-Term Debt Due in One Year       384
Derivative Assets - Current       539
Derivative Assets Long-Term       583
Gains/Losses on Derivatives and Hedging       629
Derivative Liabilities- Current       541
Derivative Liabilities Long-Term       596
Dilution Adjustment       12
Dilution Available - Excluding Extraordinary Items       12
Debt in Current Liabilities       15
Long-Term Debt - Total       13
Discontinued Operations       8
Accumulated Depreciation of RE Property       844
Depreciation, Depletion and Amortization (Accumulated)       119
Depreciation and Amortization - Total       14
Depr/Amort of Property       844
Deferred Revenue - Current       168
Deferred Revenue - Long-term       140
Extinguishment of Debt After-tax       722
Extinguishment of Debt Diluted EPS Effect       725
Extinguishment of Debt Basic EPS Effect       725
Extinguishment of Debt Pretax       710
Dividends & Interest Receivable (Cash Flow)       836
Earnings Per Share (Diluted) - Excluding Extraordinary Items - 12 Months Moving       22
Earnings Per Share (Diluted) - Including Extraordinary Items 12MM       22
Earnings Per Share (Diluted) - Including Extraordinary Items       12
Earnings Per Share (Diluted) - Excluding Extraordinary items       12
Earnings Per Share (Basic) - Including Extraordinary Items - 12 Months Moving       22
Earnings Per Share (Basic) - Including Extraordinary Items       12
Earnings Per Share (Basic) - Excluding Extraordinary Items       12
Earnings Per Share (Basic) - Excluding Extraordinary Items - 12 Months Moving       22
Preferred ESOP Obligation - Non-Redeemable       97
Preferred ESOP Obligation - Redeemable       98
Equity in Earnings (I/S) - Unconsolidated Subsidiaries       768
Foreign Exchange Income (Loss)       595
Funds From Operations (REIT)       844
Finance Division Other Current Assets, Total       844
Finance Division Other Long-Term Assets, Total       844
Finance Division - Cash       844
Finance Division Long-Term Debt  Current       844
Finance Division Debt  Long-Term       844
Finance Division  Short-Term Investments       844
Finance Division Other Current Liabilities, Total       844
Finance Division Other Long Term Liabilities, Total       844
Finance Division Notes Payable       844
Finance Division  Current Receivables       844
Finance Division  Long-Term Receivables       844
Finance Division Revenue       844
Finance Division Interest Expense       844
Finance Division Operating Expense       844
Amortization of Goodwill       844
Impairments of Goodwill AfterTax - 12mm       778
Impairment of Goodwill After-tax       816
Impairments Diluted EPS - 12mm       778
Impairment of Goodwill Diluted EPS Effect       816
Impairment of Goodwill Basic EPS Effect 12MM       778
Impairment of Goodwill Basic EPS Effect       817
Impairment of Goodwill Pretax       813
Goodwill (net)       108
Gain/Loss After-Tax       765
Gain/Loss on Sale (Core Earnings Adjusted) After-tax 12MM       410
Gain/Loss on Sale (Core Earnings Adjusted) After-tax       520
Gain/Loss on Sale (Core Earnings Adjusted) Diluted EPS Effect 12MM       417
Gain/Loss on Sale (Core Earnings Adjusted) Diluted EPS       526
Gain/Loss on Sale (Core Earnings Adjusted) Basic EPS Effect 12MM       417
Gain/Loss on Sale (Core Earnings Adjusted) Basic EPS Effect       526
Gain/Loss on Sale (Core Earnings Adjusted) Pretax       473
Gain/Loss Diluted EPS Effect       779
Gain/Loss Basic EPS Effect       779
Gains/Losses on investments       819
Gain/Loss Pretax       764
Gain/Loss on Ineffective Hedges       581
Income Before Extra Items - Adj for Common Stock Equivalents - 12MM       118
Income Before Extraordinary Items - Adjusted for Common Stock Equivalents       8
Income Before Extraordinary Items - Available for Common       8
Income before Extraordinary Items and Noncontrolling Interests       91
Income Before Extraordinary Items       7
Invested Capital - Total - Quarterly       13
Interest Accrued       798
Other Intangibles       171
Intangible Assets - Total       42
Inventory - Finished Goods       691
Inventory - Other       691
Inventory - Raw Materials       691
Inventories - Total       77
Inventory - Work in Process       691
Investment and Advances - Equity       781
Investment and Advances - Other       732
Total Long-term Investments       304
Short-Term Investments- Total       42
Current Liabilities - Other - Total       14
Current Liabilities - Total       14
Long-Term Liabilities (Total)       98
Liabilities Netting & Other Adjustments       149
Liabilities Level2 (Observable)       149
Liabilities - Other       14
Liabilities - Other - Excluding Deferred Revenue       98
Liabilities Level1 (Quoted Prices)       149
Liabilities and Stockholders Equity - Total       14
Liabilities - Total and Noncontrolling Interest       14
Liabilities - Total       14
Liabilities Level3 (Unobservable)       149
Noncontrolling Interests - Nonredeemable - Balance Sheet       41
Noncontrolling Interests - Total - Balance Sheet       42
Noncontrolling Interest - Income Account       41
Accum Other Comp Inc - Marketable Security Adjustments       53
Net Charge-Offs       844
Net Interest Income (Tax Equivalent)       844
Net Interest Margin       844
Net Income (Loss)       8
Non-Operating Income (Expense) - Total       9
Nonperforming Assets - Total       844
Notes Payable       331
Nonrecurring Income Taxes Diluted EPS Effect       727
Nonrecurring Income Taxes Basic EPS Effect       730
Nonrecurring Income Taxes - After-tax       720
Order backlog       735
Earnings Per Share - Diluted - from Operations - 12MM       22
Earnings Per Share from Operations - 12 Months Moving       22
Earnings Per Share - Diluted - from Operations       12
Operating Income After Depreciation - Quarterly       11
Operating Income Before Depreciation - Quarterly       14
Earnings Per Share from Operations       12
Dividend Rate - Assumption (%)       688
Options - Fair Value of Options Granted       643
Life of Options - Assumption (# yrs)       679
Risk Free Rate - Assumption (%)       679
Volatility - Assumption (%)       679
Pretax Income       8
Provision for Loan/Asset Losses       844
Pension Core Adjustment - 12mm       331
Core Pension Adjustment Diluted EPS Effect 12MM       338
Core Pension Adjustment Diluted EPS Effect       329
Core Pension Adjustment Basic EPS Effect 12MM       338
Core Pension Adjustment Basic EPS Effect       329
Core Pension Interest Adjustment After-tax Preliminary       378
Core Pension Interest Adjustment After-tax       465
Core Pension Interest Adjustment Diluted EPS Effect Preliminary       382
Core Pension Interest Adjustment Diluted EPS Effect       469
Core Pension Interest Adjustment Basic EPS Effect Preliminary       382
Core Pension Interest Adjustment Basic EPS Effect       469
Core Pension Interest Adjustment Pretax Preliminary       378
Core Pension Interest Adjustment Pretax       465
Core Pension Adjustment 12MM Diluted EPS Effect Preliminary       228
Core Pension Adjustment Diluted EPS Effect Preliminary       222
Core Pension Adjustment 12MM Basic EPS Effect Preliminary       228
Core Pension Adjustment Basic EPS Effect Preliminary       222
Core Pension Adjustment Preliminary       218
Core Pension Adjustment       325
Core Pension w/o Interest Adjustment After-tax Preliminary       370
Core Pension w/o Interest Adjustment After-tax       457
Core Pension w/o Interest Adjustment Diluted EPS Effect Preliminary       374
Core Pension w/o Interest Adjustment Diluted EPS Effect       461
Core Pension w/o Interest Adjustment Basic EPS Effect Preliminary       374
Core Pension w/o Interest Adjustment Basic EPS Effect       461
Core Pension w/o Interest Adjustment Pretax Preliminary       370
Core Pension w/o Interest Adjustment Pretax       457
Property, Plant and Equipment - Total (Gross) - Quarterly       119
Property Plant and Equipment - Total (Net)       25
Core Post Retirement Adjustment       325
Core Post Retirement Adjustment Diluted EPS Effect 12MM       338
Core Post Retirement Adjustment Diluted EPS Effect       329
Core Post Retirement Adjustment 12MM       331
Core Post Retirement Adjustment Basic EPS Effect 12MM       338
Core Post Retirement Adjustment Basic EPS Effect       329
Core Post Retirement Adjustment 12MM Diluted EPS Effect Preliminary       228
Core Post Retirement Adjustment Diluted EPS Effect Preliminary       222
Core Post Retirement Adjustment 12MM Basic EPS Effect Preliminary       228
Core Post Retirement Adjustment Basic EPS Effect Preliminary       222
Core Post Retirement Adjustment Preliminary       218
Repurchase Price - Average per share Quarter       250
Restructuring Cost After-tax       647
Restructuring Cost Diluted EPS Effect       655
Restructuring Cost Basic EPS Effect       655
Restructuring Cost Pretax       639
In Process R&D Expense After-tax       197
In Process R&D Expense Diluted EPS Effect       196
In Process R&D Expense Basic EPS Effect       196
In Process R&D       91
Receivables - Estimated Doubtful       420
Accum Other Comp Inc - Cumulative Translation Adjustments       82
Receivables - Current Other incl Tax Refunds       156
Receivables - Total       29
Receivables - Trade       178
Unbilled Receivables - Quarterly       837
Retained Earnings       35
Total RE Property       844
Unadjusted Retained Earnings       118
Revenue - Total       7
Reserve for Loan/Asset Losses       844
Reversal - Restructruring/Acquisition Aftertax 12MM       823

Reversal - Restructruring/Acquisition Aftertax       832
Reversal - Restructuring/Acq Diluted EPS Effect 12MM       823
Reversal - Restructuring/Acq Diluted EPS Effect       832
Reversal - Restructuring/Acq Basic EPS Effect 12MM       823
Reversal - Restructuring/Acq Basic EPS Effect       832
Reversal - Restructruring/Acquisition Pretax       832
Long-Term Restricted Cash & Investments       814
Restricted Cash & Investments - Current       788
Sales/Turnover (Net)       7
Other Stockholders- Equity Adjustments       98
Stockholders Equity > Parent > Index Fundamental > Quarterly       13
Settlement (Litigation/Insurance) AfterTax - 12mm       652
Settlement (Litigation/Insurance) After-tax       715
Settlement (Litigation/Insurance) Diluted EPS Effect 12MM       654
Settlement (Litigation/Insurance) Diluted EPS Effect       722
Settlement (Litigation/Insurance) Basic EPS Effect 12MM       654
Settlement (Litigation/Insurance) Basic EPS Effect       722
Settlement (Litigation/Insurance) Pretax       715
S&P Core Earnings 12MM       443
S&P Core Earnings EPS Diluted 12MM       450
S&P Core Earnings EPS Diluted - Preliminary       446
S&P Core Earnings EPS Diluted       446
S&P Core Earnings EPS Basic 12MM       450
S&P Core 12MM EPS - Basic - Preliminary       450
S&P Core Earnings EPS Basic - Preliminary       446
S&P Core Earnings EPS Basic       446
S&P Core Earnings 12MM - Preliminary       443
S&P Core Earnings 12MM EPS Diluted - Preliminary       450
S&P Core Earnings - Preliminary       442
S&P Core Earnings       442
Other Special Items Diluted EPS Effect       691
Other Special Items Basic EPS Effect       691
Other Special Items After-tax       688
Other Special Items Pretax       687
Special Items       37
Gain/Loss on Sale of Property       844
Stock Compensation Expense       262
After-tax stock compensation       624
Stockholders Equity - Total       13
Total Fair Value Assets       149
Total Fair Value Changes including Earnings       556
Total Fair Value Liabilities       149
Interest Expense - Total (Financial Services)       844
Interest Income - Total (Financial Services)       844
Treasury Stock - Number of Common Shares       37
Treasury Stock - Total (All Capital)       29
Deferred Tax Asset - Long Term       465
Current Deferred Tax Asset       454
Current Deferred Tax Liability       452
Deferred Taxes - Balance Sheet       269
Income Taxes - Deferred       415
Deferred Taxes and Investment Tax Credit       60
Income Taxes Payable       179
Income Taxes - Total       8
Excise Taxes       605
Current Assets - Other - Utility       732
Other Assets - Utility       732
Accounts Payable - Utility       732
Paid In Capital - Other - Utility       733
Contributions In Aid Of Construction       844
Common Equity - Total - Utility       732
Debt (Debentures) - Utility       810
Debt (Mortgage Bonds)       792
Debt (Other Long-Term)       792
Debt (Pollution Control Obligations)       792
Preferred Dividend Requirements       740
Gross Income (Income Before Interest Charges)       732
Inventories       741
Current Liabilities - Other       732
Net Income before Extraordinary Items After Noncontrolling Interest       732
Nonoperating Income (Net) - Other       732
Operating Income - Total - Utility       732
Preference Dividend Requirements - Utility       732
Premium On Common Stock - Utility       767
Premium On Preferred Stock - Utility       732
Premium On Preference Stock - Utility       732
Premium On Subsidiary Preferred Stock - Utility       732
Preference Stock At Carrying Value - Utility       732
Preferred Stock At Carrying Value - Utility       732
Receivables (Net) - Utility       732
Special Items - Utility       736
Subsidiary Preferred Dividends - Utility       732
Subsidiary Preferred Stock At Carrying Value - Utility       732
Maintenance Expense - Total       844
Working Capital (Balance Sheet)       14
Writedowns After-tax       736
Writedowns Diluted EPS Effect       741
Writedowns Basic EPS Effect       747
Writedowns Pretax       727
Accrued Expenses       431
Extraordinary Items and Discontinued Operations       8
Interest and Related Expense- Total       61
Operating Expense- Total       11
Implied Option Expense - 12mm       272
Implied Option EPS Diluted 12MM       272
Implied Option 12MM EPS Diluted Preliminary       222
Implied Option EPS Diluted       188
Implied Option EPS Diluted Preliminary       222
Implied Option EPS Basic 12MM       272
Implied Option 12MM EPS Basic Preliminary       222
Implied Option EPS Basic       188
Implied Option EPS Basic Preliminary       222
Implied Option Expense       188
Implied Option Expense Preliminary       222
Research and Development Expense       726
Selling, General and Administrative Expenses       115
Stock Exchange Code       0
CIK Number       0
Active/Inactive Status Marker       0
Current ISO Country Code - Incorporation       0

In [271]:
# 3. na values in rating
for columns in ratings.columns:
    number_of_nan(columns, ratings)

Global Company Key       0
S&P Domestic Long Term Issuer Credit Rating       130
S&P Subordinated Debt Rating       2522
S&P Domestic Short Term Issuer Credit Rating       1266
Data Date       0
Address Line 1       0
Ticker Symbol       0

In [272]:
def replace_na(df):
    for columns in df.columns:
        if df[columns].isnull().sum()>0:
            mean = df[columns].mean()

In [273]:
balancesheet.fillna(value=pd.np.nan, inplace=True)

In [274]:
ratings.fillna(value=pd.np.nan, inplace=True)

In [275]:
balancesheet = balancesheet.fillna(balancesheet.mean())

In [276]:
ratings = ratings.fillna(ratings.mean())

In [277]:
balancesheet.head()

,Global Company Key,Data Date,Fiscal Year,Fiscal Quarter,Fiscal Year-end Month,Industry Format,Level of Consolidation - Company Interim Descriptor,Population Source,Data Format,Ticker Symbol,...,Implied Option EPS Basic,Implied Option EPS Basic Preliminary,Implied Option Expense,Implied Option Expense Preliminary,Research and Development Expense,"Selling, General and Administrative Expenses",Stock Exchange Code,CIK Number,Active/Inactive Status Marker,Current ISO Country Code - Incorporation
0,1380,20100331,2010,1,12,INDL,C,D,STD,HES,...,0.0,0.0,0.0,0.0,212.695237,559.0,11,4447,A,USA
1,1380,20100630,2010,2,12,INDL,C,D,STD,HES,...,0.0,0.0,0.0,0.0,212.695237,576.0,11,4447,A,USA
2,1380,20100930,2010,3,12,INDL,C,D,STD,HES,...,0.0,0.0,0.0,0.0,212.695237,608.0,11,4447,A,USA
3,1380,20101231,2010,4,12,INDL,C,D,STD,HES,...,0.0,0.0,0.0,0.0,212.695237,805.0,11,4447,A,USA
4,1380,20110331,2011,1,12,INDL,C,D,STD,HES,...,0.0,0.0,0.0,0.0,212.695237,760.0,11,4447,A,USA

In [278]:
# 4. Normalize the table
bs1 = balancesheet.select_dtypes(include=[np.number])

In [279]:
bs1.columns

Index(['Global Company Key', 'Data Date', 'Fiscal Year', 'Fiscal Quarter',
       'Fiscal Year-end Month',
       'Accumulated Other Comprehensive Income (Loss)',
       'Current Assets - Other - Total', 'Current Assets - Total',
       'Other Long-term Assets', 'Non-Current Assets - Total',
       ...
       'Implied Option EPS Basic 12MM',
       'Implied Option 12MM EPS Basic Preliminary', 'Implied Option EPS Basic',
       'Implied Option EPS Basic Preliminary', 'Implied Option Expense',
       'Implied Option Expense Preliminary',
       'Research and Development Expense',
       'Selling, General and Administrative Expenses', 'Stock Exchange Code',
       'CIK Number'],
      dtype='object', length=356)

In [280]:
# Dropped columns Global Company Key and Data Date because it is being used in merge df

bs1 = bs1.drop(columns=['Global Company Key', 'Data Date'],axis = 1)

In [281]:
bs1.columns

Index(['Fiscal Year', 'Fiscal Quarter', 'Fiscal Year-end Month',
       'Accumulated Other Comprehensive Income (Loss)',
       'Current Assets - Other - Total', 'Current Assets - Total',
       'Other Long-term Assets', 'Non-Current Assets - Total',
       'Assets Netting & Other Adjustments',
       'Accum Other Comp Inc - Derivatives Unrealized Gain/Loss',
       ...
       'Implied Option EPS Basic 12MM',
       'Implied Option 12MM EPS Basic Preliminary', 'Implied Option EPS Basic',
       'Implied Option EPS Basic Preliminary', 'Implied Option Expense',
       'Implied Option Expense Preliminary',
       'Research and Development Expense',
       'Selling, General and Administrative Expenses', 'Stock Exchange Code',
       'CIK Number'],
      dtype='object', length=354)

In [282]:
bs = (bs1 - bs1.mean()) / (bs1.max() - bs1.min())

In [283]:
balancesheet[bs.columns] = bs

In [284]:
balancesheet.head()

,Global Company Key,Data Date,Fiscal Year,Fiscal Quarter,Fiscal Year-end Month,Industry Format,Level of Consolidation - Company Interim Descriptor,Population Source,Data Format,Ticker Symbol,...,Implied Option EPS Basic,Implied Option EPS Basic Preliminary,Implied Option Expense,Implied Option Expense Preliminary,Research and Development Expense,"Selling, General and Administrative Expenses",Stock Exchange Code,CIK Number,Active/Inactive Status Marker,Current ISO Country Code - Incorporation
0,1380,20100331,-0.431787,-0.500000,0.033175,INDL,C,D,STD,HES,...,NaN,NaN,NaN,NaN,4.307605e-16,0.029708,NaN,-0.399124,A,USA
1,1380,20100630,-0.431787,-0.166667,0.033175,INDL,C,D,STD,HES,...,NaN,NaN,NaN,NaN,4.307605e-16,0.033497,NaN,-0.399124,A,USA
2,1380,20100930,-0.431787,0.166667,0.033175,INDL,C,D,STD,HES,...,NaN,NaN,NaN,NaN,4.307605e-16,0.040630,NaN,-0.399124,A,USA
3,1380,20101231,-0.431787,0.500000,0.033175,INDL,C,D,STD,HES,...,NaN,NaN,NaN,NaN,4.307605e-16,0.084539,NaN,-0.399124,A,USA
4,1380,20110331,-0.288930,-0.500000,0.033175,INDL,C,D,STD,HES,...,NaN,NaN,NaN,NaN,4.307605e-16,0.074509,NaN,-0.399124,A,USA

In [285]:
"""
5. Calculate the correlation matrix for variables = [’Current Assets - Other - To- tal’,
’Current Assets - Total’, ’Other Long-term Assets’, 
’Assets Netting Other Adjustments’].
"""

correlation_matrix = balancesheet[['Current Assets - Other - Total','Current Assets - Total', 'Other Long-term Assets', 'Assets Netting & Other Adjustments']].corr()
correlation_matrix

,Current Assets - Other - Total,Current Assets - Total,Other Long-term Assets,Assets Netting & Other Adjustments
Current Assets - Other - Total,1.000000,0.790047,0.629802,0.042504
Current Assets - Total,0.790047,1.000000,0.665006,-0.072010
Other Long-term Assets,0.629802,0.665006,1.000000,-0.017979
Assets Netting & Other Adjustments,0.042504,-0.072010,-0.017979,1.000000

In [286]:
# iterable function
def get_last_name(name):
    return name.split()[-1]

In [287]:
""" 
6. New column (Name: ’CO’) to store the last word of company name. 
"""

last_name = balancesheet['Company Name'].map(get_last_name)
balancesheet['CO'] = last_name
balancesheet['CO']

0      CORP
1      CORP
2      CORP
3      CORP
4      CORP
       ...
839    CORP
840    CORP
841    CORP
842    CORP
843    CORP
Name: CO, Length: 844, dtype: object

In [288]:
"""
7. Merge (inner) Ratings and BalanceSheet based on ’datadate’ and ’Global Com- pany Key’, 
and name merged dataset ’Matched’.
"""
Matched = pd.merge(ratings, balancesheet, on=['Data Date','Global Company Key'], how='inner')

In [289]:
Matched.head()

,Global Company Key,S&P Domestic Long Term Issuer Credit Rating,S&P Subordinated Debt Rating,S&P Domestic Short Term Issuer Credit Rating,Data Date,Address Line 1,Ticker Symbol_x,Fiscal Year,Fiscal Quarter,Fiscal Year-end Month,...,Implied Option EPS Basic Preliminary,Implied Option Expense,Implied Option Expense Preliminary,Research and Development Expense,"Selling, General and Administrative Expenses",Stock Exchange Code,CIK Number,Active/Inactive Status Marker,Current ISO Country Code - Incorporation,CO
0,1380,BBB-,NaN,NaN,20100331,"1185 Avenue of the Americas, 40th Floor",HES,-0.431787,-0.500000,0.033175,...,NaN,NaN,NaN,4.307605e-16,0.029708,NaN,-0.399124,A,USA,CORP
1,1380,BBB-,NaN,NaN,20100630,"1185 Avenue of the Americas, 40th Floor",HES,-0.431787,-0.166667,0.033175,...,NaN,NaN,NaN,4.307605e-16,0.033497,NaN,-0.399124,A,USA,CORP
2,1380,BBB,NaN,NaN,20100930,"1185 Avenue of the Americas, 40th Floor",HES,-0.431787,0.166667,0.033175,...,NaN,NaN,NaN,4.307605e-16,0.040630,NaN,-0.399124,A,USA,CORP
3,1380,BBB,NaN,NaN,20101231,"1185 Avenue of the Americas, 40th Floor",HES,-0.431787,0.500000,0.033175,...,NaN,NaN,NaN,4.307605e-16,0.084539,NaN,-0.399124,A,USA,CORP
4,1380,BBB,NaN,NaN,20110331,"1185 Avenue of the Americas, 40th Floor",HES,-0.288930,-0.500000,0.033175,...,NaN,NaN,NaN,4.307605e-16,0.074509,NaN,-0.399124,A,USA,CORP

In [290]:
#8. Mapping
def numerical_rating(rate):
    if rate == 'AAA':
        return 0
    elif rate == 'AA+':
        return 1     
    elif rate == 'AA':
        return 2
    elif rate == 'AA-':
        return 3
    elif rate == 'A+':
        return 4
    elif rate == 'A':
        return 5
    elif rate == 'A-':
        return 6
    elif rate == 'BBB+':
        return 7
    elif rate == 'BBB':
        return 8
    elif rate == 'BBB-':
        return 9
    elif rate == 'BB+':
        return 10
    elif rate == 'BB':
        return 11
    else:
        return 12
    
Matched['Rate'] = Matched['S&P Domestic Long Term Issuer Credit Rating'].map(numerical_rating)
Matched['Rate']

0      9
1      9
2      8
3      8
4      8
      ..
817    8
818    8
819    8
820    8
821    8
Name: Rate, Length: 822, dtype: int64

In [291]:
# 9. the rating frequency of company whose name end with ’CO’
Matched[Matched['CO']=='CO']['Rate'].value_counts()

9     50
10    29
5     25
11     5
7      2
6      1
Name: Rate, dtype: int64

In [292]:
# 10. Output your final dataset as ’HW4.csv’
Matched.to_csv("~/Desktop/files/Homework4_Dataset/HW4.csv",index=False)